#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII

bspc config border_width         0
bspc config window_gap           5.5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

#Startup
sxhkd &
polybar left &
polybar center &
polybar right &
nitrogen --restore &
dunst &
xautolock -time 10 -locker ~/.config/scripts/lock &
